nginx:
    build: ./nginx
    links:
        - shinyserv1:shinyserv1
        - shinyserv2:shinyserv2
        - shinyserv3:shinyserv3
    ports:
        - "80:80"
shinyserv1:
    build: kuzmenkov/shinyserv
    ports:
        - "3838"
shinyserv2:
    build: kuzmenkov/shinyserv
    ports:
        - "3838"
shinyserv3:
    build: kuzmenkov/shinyserv
    ports:
        - "3838"
